/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Language: typeof import('./src/components/language/index.vue')['default']
    LogoIcon: typeof import('./src/components/icon/logoIcon.vue')['default']
    NestedTable: typeof import('./src/components/nested-table/nested-table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
